# Generated by Django 3.2.12 on 2022-03-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_delivery_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
