# Generated by Django 3.2.12 on 2022-03-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_create_dish_ingredient_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishingredient',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
