# Generated by Django 3.2.12 on 2022-04-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_add_restaurant_to_ingredient_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='dish.DishIngredient', to='dish.Ingredient'),
        ),
    ]
