# Generated by Django 3.2.12 on 2022-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_dish_ingredients_through_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dish_pictures/'),
        ),
    ]
