# Generated by Django 3.2.12 on 2022-03-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_create_user_and_role_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
