# Generated by Django 3.2.12 on 2022-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_nullable_branch_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authentication_provider',
            field=models.TextField(default='django'),
        ),
    ]
