# Generated by Django 3.2.12 on 2022-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_first_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='front_picture',
            field=models.ImageField(blank=True, null=True, upload_to='branch_front_pictures/'),
        ),
    ]
