# Generated by Django 3.2.12 on 2022-04-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_create_inventory_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('branch', 'ingredient'), name='branch_ingredient'),
        ),
    ]
