# Generated by Django 3.2.12 on 2022-04-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_promotion_dishes_through_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='ingredients',
            new_name='available_ingredients',
        ),
    ]
