# Generated by Django 3.2.12 on 2022-04-11 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_add_restaurant_to_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='finish_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
