# Generated by Django 3.2.12 on 2022-04-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0011_created_at_finished_at_promotion_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='finish_at',
            new_name='finish_date',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
