# Generated by Django 3.2.12 on 2022-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_types',
            field=models.ManyToManyField(to='restaurant.DeliveryType'),
        ),
    ]
