# Generated by Django 3.2.12 on 2022-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_created_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='position_order',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
