# Generated by Django 3.2.12 on 2022-04-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_create_dish_category_model'),
        ('order', '0005_order_status_position_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurant.deliverytype'),
            preserve_default=False,
        ),
    ]
