# Generated by Django 3.2.12 on 2022-04-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_delivery_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='position_order',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='previous_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
            preserve_default=False,
        ),
    ]
