# Generated by Django 3.2.12 on 2022-04-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_status_previous_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
        ),
    ]
