# Generated by Django 3.2.12 on 2022-04-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_create_combo_model'),
        ('restaurant', '0004_create_dish_category_model'),
        ('authentication', '0003_add_managers_to_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.CheckConstraint(check=models.Q(('restaurant__isnull', False), ('branch__isnull', False), _connector='OR'), name='employee_profile_restaurant_branch_both_not_null'),
        ),
    ]
