# Generated by Django 3.2.12 on 2022-04-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_create_combo_model'),
        ('restaurant', '0004_create_dish_category_model'),
        ('authentication', '0004_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
