# Generated by Django 3.2.12 on 2022-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_authentication_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_password_token',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='change_password_token'),
        ),
    ]
