# Generated by Django 3.2.12 on 2022-04-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_dish_ingredients_through_relationship'),
        ('branch', '0006_create_combo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ingredients',
            field=models.ManyToManyField(through='branch.Inventory', to='dish.Ingredient'),
        ),
    ]
